### PR TITLE
Custom persona with wrong image size is applied anyway

### LINKED ISSUE #72: Custom persona with wrong image size is applied anyway.
Just try to apply a custom persona with an invalid image size. The warning dialog appears but the persona is applied anyway.

### PR DESCRIPTION
**Pull request by derinb**
Custom persona with wrong image size is applied anyway

Fixes #72

### CODE REVIEW

File: extension/content/customPersonaEditor.js [hunk 1]
```diff
@@ -228,16 +228,16 @@ var CustomPersonaEditor = {
...
               }
-              return;
+          }
+          else{
+            // A random number is appended to avoid displaying a cached image
+            // after the image has been modified.
+            // See: https://bugzilla.mozilla.org/show_bug.cgi?id=543333
+            control.value = this.customPersona[property] =
+                fp.fileURL.spec + "?" + Math.floor(Math.random() * 10000);
+            this._save();
```
Comment (wagnerand) [inline extension/content/customPersonaEditor.js]: Formatting (again)...

**Comment by derinb** [comment]
Updated
