### PR TITLE
Handle Theme for Disable and Uninstall

### LINKED ISSUE #50: Removing Personas Plus will also remove the enabled theme instead of default theme
Steps to reproduce:

1.Install the Personas Plus version 1.8.0b3 add-on.
2.Install some themes from “Featured”.
3.Go to about:addons and remove Personas Plus.

Expected results:
The default theme from Personas Plus (Groovy Blue) is removed.

Actual results:
The theme applied by default by Personas plus (Groovy Blue) is not removed.

Note/Issues:
Verified on FF48.0b7(Win 7 64-bit)
This issue is reproducing in AMO production server

Here is a video:
lasttheme

### PR DESCRIPTION
**Pull request by derinb**
When PP is disabled or uninstalled, a confirmation box will ask user to
remove the active theme or not.

When uninstall takes place, if the active theme is Groovy Blue, it will
be removed automatically.

Fixes #50

### CODE REVIEW

File: extension/bootstrap.js [hunk 1]
```diff
@@ -78,20 +78,23 @@ var PersonasPlusBootstrapAddon = {
...
-            try {
-                Cu.import("resource://gre/modules/LightweightThemeManager.jsm");
-            } catch (e) {
-                LightweightThemeManager = null;
-            }
-            try {
-                LightweightThemeManager.forgetUsedTheme(LightweightThemeManager.currentTheme.id);
-            } catch (e) {
+            var prompt = Components.classes["@mozilla.org/embedcomp/prompt-service;1"].getService(Components.interfaces.nsIPromptService);
+            if (prompt.confirm(null, "Personas Plus", "Would you like to remove current theme?")) {
```
Comment (wagnerand) [inline extension/bootstrap.js]: The prompt should only appear if the current theme is not _Groovy Blue_.

Also, please use `Would you like to remove the current theme?`

File: extension/bootstrap.js [hunk 2]
```diff
@@ -78,20 +78,23 @@ var PersonasPlusBootstrapAddon = {
...
+                    Cu.import("resource://gre/modules/LightweightThemeManager.jsm");
+                } catch (e) {
+                    LightweightThemeManager = null;
+                }
+                try {
+                    LightweightThemeManager.forgetUsedTheme(LightweightThemeManager.currentTheme.id);
+                } catch (e) {
+                    try {
+                        LightweightThemeManager.currentTheme = null;
+                    } catch (e) {}
```
Comment (wagnerand) [inline extension/bootstrap.js]: While you're at it, could you clean this up, please? There is no need to wrap each line in a `try-catch` block.

File: extension/bootstrap.js [hunk 3]
```diff
@@ -255,10 +258,11 @@ function uninstall(data, reason) {
         LightweightThemeManager = null;
     }
     try {
-        LightweightThemeManager.forgetUsedTheme(LightweightThemeManager.currentTheme.id);
+        //Remove Groovy Blue Theme
+        LightweightThemeManager.forgetUsedTheme("15131");
     } catch (e) {
         try {
-            LightweightThemeManager.currentTheme = null;
+            //LightweightThemeManager.currentTheme = null;
```
Comment (wagnerand) [inline extension/bootstrap.js]: What's the reason for this?

File: extension/bootstrap.js (hunk 1 above)
Comment (mustaim) [inline extension/bootstrap.js]: But when add-on is disabled, user may want to remove Light Weight theme, so that she can use the default theme. So this prompt should be available for all cases, I suppose.

What do you think?

**Comment by derinb** [comment]
Updated

File: extension/bootstrap.js [hunk 4]
```diff
@@ -78,20 +74,18 @@ var PersonasPlusBootstrapAddon = {
...
-            } catch (e) {
-                try {
-                    LightweightThemeManager.currentTheme = null;
-                } catch (e) {}
+            if(LightweightThemeManager.currentTheme){
+                var prompt = Components.classes["@mozilla.org/embedcomp/prompt-service;1"].getService(Components.interfaces.nsIPromptService);
+                if (prompt.confirm(null, "Personas Plus", "Would you like to remove the current theme?")) {
+                    try {
+                        Cu.import("resource://gre/modules/LightweightThemeManager.jsm");
+                        LightweightThemeManager.forgetUsedTheme(LightweightThemeManager.currentTheme.id);
```
Comment (wagnerand) [inline extension/bootstrap.js]: So, what happens if _Groovy Blue_ is the current theme?

If the answer is _yes_, either this line or line 245 will fail.
If the answer is _no_, _Groovy Blue_ will be removed because of line 245 despite the fact that the answer was _no_.

Comment (derinb) [inline extension/bootstrap.js]: Line 245 is the actual uninstall case. When complete uninstall happens, Groovy Blue is removed, whether it is active or disabled. In issue, you commented as:

> "If Groovy Blue is not the current theme, let's remove it anyway."

So I do not check whether it is active or not, just Groovy Blue is removed for uninstall case. It is default theme and should be removed if add-on is removed.

Otherwise there are too many combinations to handle which are not necessary for uninstall/disable events. If she wants to keep Groovy Blue, she can manually download from AMO.

BTW, LightweightThemeManager.forgetUsedTheme does not throw error, if the theme id is not available. It just silently fails.

Comment (wagnerand) [inline extension/bootstrap.js]: > BTW, LightweightThemeManager.forgetUsedTheme does not throw error, if the theme id is not available. It just silently fails.

OK, good to know.

But, if you explicitly ask the user if the current theme should be uninstalled (and that theme happens to be _Groovy Blue_), you should not remove if the user answered _no_.

That's why I suggested to call this routine only if _Groovy Blue_ is not the current theme.

Comment (derinb) [inline extension/bootstrap.js]: OK, great point. Let me implement it.

**Comment by derinb** [comment]
Updated. Prompt is only for non-Groovy themes. 

For disable event, Groovy will be removed without prompt.

File: extension/bootstrap.js [hunk 5]
```diff
@@ -78,20 +74,23 @@ var PersonasPlusBootstrapAddon = {
...
-                LightweightThemeManager = null;
-            }
-            try {
-                LightweightThemeManager.forgetUsedTheme(LightweightThemeManager.currentTheme.id);
-            } catch (e) {
-                try {
-                    LightweightThemeManager.currentTheme = null;
-                } catch (e) {}
+            if (LightweightThemeManager.currentTheme) {
+                if (LightweightThemeManager.currentTheme.id != "15131") {
```
Comment (wagnerand) [inline extension/bootstrap.js]: `if (LightweightThemeManager.currentTheme && LightweightThemeManager.currentTheme.id != "15131") {`

File: extension/bootstrap.js [hunk 6]
```diff
@@ -78,20 +74,23 @@ var PersonasPlusBootstrapAddon = {
...
+                            LightweightThemeManager.forgetUsedTheme(LightweightThemeManager.currentTheme.id);
+                        } catch (e) {
+                            try {
+                                LightweightThemeManager.currentTheme = null;
+                            } catch (e) {}
+                        }
+                    }
+                } else {
+                    // Remove Groovy Blue Theme
+                    LightweightThemeManager.forgetUsedTheme("15131");
```
Comment (wagnerand) [inline extension/bootstrap.js]: I think either this or line 250 is unnecessary? Why do it twice?

File: extension/bootstrap.js (hunk 5 above)
Comment (derinb) [inline extension/bootstrap.js]: yes because of else...

File: extension/bootstrap.js (hunk 6 above)
Comment (derinb) [inline extension/bootstrap.js]: you are right, 250 is unnecessary.

When clicking Disable button, theme should be removed. But uninstall function only runs after about:addons page is closed. So it should be handled in Shutdown function.

**Comment by derinb** [comment]
Updated. Removed 250 code.

File: extension/bootstrap.js [hunk 7]
```diff
@@ -242,25 +241,6 @@ function uninstall(data, reason) {
         .getService(Components.interfaces.nsIPrefService).getBranch("extensions.personas.").deleteBranch("");
     Components.classes["@mozilla.org/intl/stringbundle;1"]
         .getService(Components.interfaces.nsIStringBundleService).flushBundles();
```
Comment (wagnerand) [inline extension/bootstrap.js]: I feel like those lines could be included in `shutdown` above as well and we could eliminate this function. Out of the scope for this bug though, but a thing we can keep in mind.

**Comment by wagnerand** [comment]
Thanks!
