### PR TITLE
Remove flag for custom persona

### LINKED ISSUE #43: Disabling custom personas does not remove the custom persona displayed in browser
Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
Personas Plus version 1.8.0b1

### Steps to reproduce:
1. Go to tools - Personas - Preferences and enable custom personas
2. go to tools - Personas - Custom Persona and click the Edit button
3. Upload a header image and apply the custom persona
4. Go again to preferences and disable the custom personas

### Expected results:
The custom persona is disabled and the browser comes back to the default theme

### Actual results:
The custom persona is still displayed.

Screencast for this issue:
custompersonasdisable

### PR DESCRIPTION
**Pull request by wagnerand**
This removes the flag for custom persona and thus enables it by default.
Fixes #43

### CODE REVIEW

**Comment by wagnerand** [comment]
@derinb can you give this a quick look, please?

File: extension/modules/personas.js [hunk 1]
```diff
@@ -1123,8 +1123,8 @@ var PersonaController = {
         // Update the Custom menu. Custom personas unavailable in per-window
         // personas mode.
         let customMenu = document.getElementById("personas-plus-custom-menu");
-        customMenu.hidden = this._prefs.get("perwindow") || !this._prefs.get("showCustomMenu");
-        if (!customMenu.hidden) {
+        customMenu.disabled = this._prefs.get("perwindow")
```
Comment (derinb) [inline extension/modules/personas.js]: `customMenu.hidden` is better, I suppose. I created a Custom Persona with name, toggled `perwindow` pref to `true` and checked toolbar menu. Custom menu displays as blank.

Comment (wagnerand) [inline extension/modules/personas.js]: Hiding content is generally considered bad user experience. It's better to disable them if they are not available.

Comment (derinb) [inline extension/modules/personas.js]: OK, but then you need to handle this STR because Custom menu label is blank:

1. Create Custom Persona with name
2. Toggle `perwindow` pref to `true`
3. Check toolbar button menu and see the Custom label is empty

Comment (wagnerand) [inline extension/modules/personas.js]: Hm, works for me.

screen shot 2016-07-16 at 22 53 05

Comment (derinb) [inline extension/modules/personas.js]: Sorry yes works for me, too. Probably I did not write the steps correctly.

What about when you open New Window:

1.     Create Custom Persona with name
2.     Toggle perwindow pref to true
3.     Check toolbar button menu. Label is there.
4.     Open New Window
5.     Check toolbar button menu. Label is empty.

Comment (wagnerand) [inline extension/modules/personas.js]: Ugh, redeclaration of `let name`....

**Comment by wagnerand** [comment]
Ok, fixed. Thanks!

**Comment by derinb** [comment]
Works great, thank you.
