### PR TITLE
Theme Info Bar Undo Fix

### LINKED ISSUE #82: Theme info bar cannot be dismissed by clicking the "Undo" button after uninstalling Persona Plus
Clones from https://bugzilla.mozilla.org/show_bug.cgi?id=1313673:

Steps to reproduce:
1. Install attached "Persona Plus" add-on from about:addons
2. Remove the "Persona Plus"
3. Click the "Undo" button from the info bar

Expected results:
The info bar is dismissed.

Actual results:
Nothing happens.

Notes/Issues:
Reproducing also if add-on is disabled.
Verified on FF49.0.2 using Windows 7 x64
Screencast for this issue: http://screencast.com/t/0SsFZnIVdrMj

/cc @ValentinaPC

### PR DESCRIPTION
**Pull request by derinb**
Theme info bar can be dismissed by clicking the Undo button after
uninstalling PP by this commit. Fixes #82

### CODE REVIEW

**Comment by wagnerand** [comment]
Hm, I don't understand how that patch resolves the issue. Can you explain, please?

**Comment by derinb** [comment]
When uninstalled or disabled, all scripts unloaded. PersonaService is not available any more. If clicked, error is thrown which prevents the execution to successfully complete attached Undo callback. That is why Undo does not dismiss the notification bar. It halts at

`PersonaService.revertToPreviousPersona();`

line.

By try and catch block, we can detect the uninstall and disable case. If there is no PersonaService available, nothing is executed and notification bar is simply dismissed.

Alternatively, an add-on listener should be attached for listening uninstall and disable which would close all notification bars automatically. But it is not necessary to add extra memory for such a rare bug. Try and catch is enough for this minor bug.

**Comment by wagnerand** [comment]
> Alternatively, an add-on listener should be attached for listening uninstall and disable which would close all notification bars automatically. But it is not necessary to add extra memory for such a rare bug.

This is the way we should be going. The add-on is responsible for adding the notification, so it should be for cleaning it up. Also, it's quite surprising if you click on the 'Undo' button and nothing happens.

It shouldn't be a big deal to check the notification bar in the uninstall handler. I don't think we would need extra memory for that?

**Comment by derinb** [comment]
Updated. Removing all notifications bar at shutdown automatically.

File: extension/bootstrap.js [hunk 1]
```diff
@@ -93,6 +93,28 @@ var PersonasPlusBootstrapAddon = {
...
+                    var not1 = gBrowser.getNotificationBox(b).getNotificationWithValue("personas-plus-private-browsing-warning");
+                    if (not1) {
+                        gBrowser.getNotificationBox(b).removeNotification(not1);
+                    }
+                    var not2 = gBrowser.getNotificationBox(b).getNotificationWithValue("lwtheme-install-notification");
+                    if (not2) {
+                        gBrowser.getNotificationBox(b).removeNotification(not2);
+                    }
+                } catch (e) {
+                    //foo
```
Comment (wagnerand) [inline extension/bootstrap.js]: Nit: Why is `try-catch` needed here? What can go wrong? It _might_ be ok to swallow exceptions, but in any case, we should get rid of the `//foo` comment.

**Comment by derinb** [comment]
Updated. Thanks

**Comment by wagnerand** [comment]
Great, thank you!
