### PR TITLE
Restrict Specific Dimensions and File Types  for header and footer when creating Cusom Personas

### LINKED ISSUE #54: Users can use any dimensions and file types for header and footer when creating Cusom Personas
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0
FF : 48.0b7

Steps to reproduce:
1.Install latest Personas Plus from https://addons.mozilla.org/en-US/firefox/addon/personas-plus/#beta-channel
2.From Personas Plus drop down menu , select "Custom Persona"- "Edit" 
3.Add different dimensions and file types for header and footer 

Expected results:
User is warned that only specific dimensions and file types are supported

Actual results:
No warnings displayed for wrong file types and also , no specific dimensions are enforced and this will lead to ugly personas

Please see video for this bug :   http://screencast.com/t/vatShGOdbnp0

We should use something like this when creating Custom Personas :  
dimensions

### PR DESCRIPTION
**Pull request by derinb**
Restrict Specific Dimensions (3000 x 200) and File Types (png, jpg)
for header and footer when creating Custom Personas. 

A confirm prompt is provided for Mozilla page which tells how to create custom persona in details.

Fixes #54

### CODE REVIEW

File: extension/content/customPersonaEditor.js [hunk 1]
```diff
@@ -213,12 +213,25 @@ var CustomPersonaEditor = {
     let property = control.id;
 
     let fp = Cc["@mozilla.org/filepicker;1"].createInstance(Ci.nsIFilePicker);
+    fp.appendFilter("Images", "*.png; *.jpg");
```
Comment (wagnerand) [inline extension/content/customPersonaEditor.js]: Can you add `"*.jpeg"` as well, please?

File: extension/content/customPersonaEditor.js [hunk 2]
```diff
@@ -213,12 +213,25 @@ var CustomPersonaEditor = {
...
     fp.init(window,
             this._strings.get("backgroundPickerDialogTitle"),
             Ci.nsIFilePicker.modeOpen);
     let result = fp.show();
 
     if (result == Ci.nsIFilePicker.returnOK) {
+      var img = new Image();
+      img.src = fp.fileURL.spec;
+      img.onload = function() {
+          if (img.naturalWidth != 3000 && img.naturalHeight != 200) {
```
Comment (wagnerand) [inline extension/content/customPersonaEditor.js]: I think you want `||` instead of `&&` here.

Also, please use non-casting comparators, ie `!==`.

**Comment by derinb** [comment]
Updated

**Comment by wagnerand** [comment]
Thanks!
